### ISSUE TITLE
Critical documentation error

### ISSUE THREAD

**Issue by simonboydfoley** [ryanhay/ocp4-metal-install#5]
I don't know if this was introduced with  Openshift 4.7   ... but you need to change the kernel boot arguments otherwise it will fail to boot with missing gpg sig files that you can not get hold of ...

The official documents state ...

"If you are using coreos.inst.image_url, you must also use coreos.inst.insecure. This is because the bare-metal media are not GPG-signed for OpenShift Container Platform."

>> Your kernal boot documentation is omitting the final 

coreos.inst.insecure

!!!
Took me 2 weeks to figure out ... I kept trying to sign the image files with the ssh-keygen which is impossible currently with the tools in RHEL 8.

**Comment by ryanhay** [comment]
Thanks for pointing this out, it must be new in 4.7. I have updated the repo.
